export const MILL_FABRICS = [
  { name: "Rayon", base: "Rayon", width: '44"', type: "Mill" },
  { name: "Rayon", base: "Rayon", width: '58"', type: "Mill" },
  { name: "Capsule Rayon", base: "Rayon x Poly", width: '44"', type: "Mill" },
  { name: "Capsule Rayon", base: "Rayon x Poly", width: '58"', type: "Mill" },
  { name: "Berlin", base: "PV", width: '58"', type: "Mill" },
  { name: "Vatican", base: "PV", width: '58"', type: "Mill" },
  { name: "Modal Chanderi", base: "PV", width: '44"', type: "Mill" },
  { name: "Modal Chanderi", base: "PV", width: '58"', type: "Mill" },
  { name: "Cotton Camric", base: "Cotton", width: '58"', type: "Mill" },
  { name: "Cotton Mul", base: "Cotton", width: '44"', type: "Mill" },
  { name: "Mul Chanderi", base: "Viscose", width: '58"', type: "Mill" },
  { name: "Cotton Flex", base: "Cotton", width: '44"', type: "Mill" },
  { name: "Cotton Slub", base: "Cotton", width: '44"', type: "Mill" },
  { name: "Rayon Slub Lycra", base: "Rayon", width: '50"', type: "Mill" },
  { name: "Rayon Wrinkle Crape", base: "Rayon", width: '56"', type: "Mill" },
  { name: "Weightless", base: "Poly", width: '58"', type: "Mill" },
  { name: "BSY Killer", base: "Poly", width: '58"', type: "Mill" },
  { name: "Orange Wrinkle Chiffon", base: "Poly", width: '56"', type: "Mill" },
  { name: "Delta", base: "Poly", width: '58"', type: "Mill" },
  { name: "Inbox", base: "Poly", width: '58"', type: "Mill" }
];

export const DIGITAL_FABRICS = [
  { name: "Viscose Chinon", base: "Viscose", width: '44"', type: "Digital" },
  { name: "Natural Crape", base: "Viscose", width: '50"', type: "Digital" },
  { name: "Viscose Organza", base: "Viscose", width: '44"', type: "Digital" },
  { name: "Viscose Muslin", base: "Viscose", width: '44"', type: "Digital" },
  { name: "Viscose Georgette", base: "Viscose", width: '44"', type: "Digital" },
  { name: "Shimmer Tissue", base: "Viscose", width: '58"', type: "Digital" },
  { name: "Glass Tissue", base: "Viscose", width: '44"', type: "Digital" },
  { name: "Habutai Silk", base: "Viscose", width: '58"', type: "Digital" },
  { name: "Gajji Silk", base: "Viscose", width: '58"', type: "Digital" },
  { name: "Dola Silk", base: "Viscose", width: '44"', type: "Digital" },
  { name: "Upada Silk", base: "Viscose", width: '44"', type: "Digital" },
  { name: "60 x 60 Cotton", base: "Cotton", width: '44"', type: "Digital" },
  { name: "Cotton Lycra", base: "Cotton", width: '58"', type: "Digital" },
  { name: "Camric Golk Jari", base: "Cotton", width: '44"', type: "Digital" },
  { name: "Cotton Mull (100x100)", base: "Cotton", width: '36"', type: "Digital" },
  { name: "Cotton Slub", base: "Cotton", width: '44"', type: "Digital" },
  { name: "Cotton Kota Chex", base: "Cotton", width: '44"', type: "Digital" },
  { name: "Cotton Camric (60x60)", base: "Cotton", width: '44"', type: "Digital" },
  { name: "Cotton Flex", base: "Cotton", width: '44"', type: "Digital" },
  { name: "Cora Cotton", base: "Cotton", width: '47"', type: "Digital" },
  { name: "Inner Mull", base: "Cotton", width: '44"', type: "Digital" },
  { name: "Cotton Tintin", base: "Cotton", width: '44"', type: "Digital" },
  { name: "Cotton Jam Satin", base: "Cotton", width: '44"', type: "Digital" },
  { name: "Organdi", base: "Cotton", width: '44"', type: "Digital" }
];

export const POLY_FABRICS = [
  { name: "Poly Linen", base: "Poly", width: '58"', type: "Digital" },
  { name: "Poly Cotton", base: "PC", width: '54"', type: "Digital" },
  { name: "Poly Organza", base: "Poly", width: '44"', type: "Digital" },
  { name: "Poly Chanderi", base: "Poly", width: '44"', type: "Digital" },
  { name: "Poly Muslin", base: "Poly", width: '36"', type: "Digital" },
  { name: "Silk Crape", base: "Poly", width: '44"', type: "Digital" },
  { name: "Japan Satin", base: "Poly", width: '44"', type: "Digital" },
  { name: "Satin Georgette", base: "Poly", width: '44"', type: "Digital" },
  { name: "French Crape", base: "Poly", width: '44"', type: "Digital" },
  { name: "Regular Chanderi", base: "Poly", width: '44"', type: "Digital" },
  { name: "Tabby Silk", base: "Poly", width: '44"', type: "Digital" },
  { name: "Poly Chinon", base: "Poly", width: '44"', type: "Digital" },
  { name: "Magic", base: "Poly", width: '44"', type: "Digital" },
  { name: "Poly Camric", base: "Poly", width: '44"', type: "Digital" },
  { name: "Indigo Silk", base: "Poly", width: '44"', type: "Digital" },
  { name: "Poly Rayon", base: "Poly", width: '44"', type: "Digital" },
  { name: "Jute", base: "Poly", width: '44"', type: "Digital" },
  { name: "Khadi Jute", base: "Poly", width: '44"', type: "Digital" },
  { name: "Poly Popline", base: "Poly", width: '58"', type: "Digital" },
  { name: "Pashmina Twill", base: "Poly", width: '44"', type: "Digital" },
  { name: "Silver Chiffon", base: "Poly", width: '36"', type: "Digital" },
  { name: "Flat Chiffon", base: "Poly", width: '44"', type: "Digital" },
  { name: "African Georgette", base: "Poly", width: '44"', type: "Digital" }
];