import * as XLSX from 'xlsx';
import { AIShortCodeGenerator } from './AIShortCodeGenerator';
import { SKUGenerator } from './SKUGenerator';

export const ExcelCSVParser = {
  ALLOWED_WIDTHS: ["28", "30", "36", "40", "44", "48", "50", "54", "56", "58", "62", "66", "72", "78"],
  
  async parseFile(file) {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      
      reader.onload = async (e) => {
        try {
          const data = new Uint8Array(e.target.result);
          const workbook = XLSX.read(data, { type: 'array' });
          const firstSheetName = workbook.SheetNames[0];
          const worksheet = workbook.Sheets[firstSheetName];
          const jsonData = XLSX.utils.sheet_to_json(worksheet, { header: 1 });

          if (jsonData.length < 2) {
             resolve({ data: [], errors: [], summary: { total: 0, valid: 0, invalid: 0 } });
             return;
          }

          const headers = jsonData[0].map(h => String(h).toLowerCase().trim());
          const rows = jsonData.slice(1);
          
          const parsedRows = [];
          const allErrors = [];
          const headerMap = this.mapHeaders(headers);
          
          let validCount = 0;
          let invalidCount = 0;
          
          // Collect all generated SKUs to check internal duplicates
          const generatedSKUs = [];

          for (let i = 0; i < rows.length; i++) {
             const row = rows[i];
             if (row.length === 0 || row.every(cell => !cell)) continue; // Skip empty rows

             const rowData = { _rowId: i + 2, _status: 'valid', _errors: [], _warnings: [] };
             
             // Extract data
             for (const [key, index] of Object.entries(headerMap)) {
                 if (index !== -1 && row[index] !== undefined) {
                     rowData[key] = String(row[index]).trim();
                 } else {
                     rowData[key] = '';
                 }
             }
             
             // Auto-generate logic
             if (!rowData.short_code && rowData.fabric_name && rowData.base) {
                 rowData.short_code = await AIShortCodeGenerator.generateShortCode(rowData.fabric_name, rowData.base);
                 rowData._auto_short_code = true;
             }
             
             if (!rowData.sku && rowData.width && rowData.short_code) {
                 rowData.sku = SKUGenerator.generateSKU(rowData.width, rowData.short_code, rowData.finish);
                 rowData._auto_sku = true;
             }

             if (rowData.sku) generatedSKUs.push(rowData.sku);

             // Validation
             const rowErrors = this.validateRow(rowData);
             if (rowErrors.length > 0) {
                 rowData._status = 'error';
                 rowData._errors = rowErrors;
                 invalidCount++;
                 allErrors.push({ row: i + 2, errors: rowErrors });
             } else {
                 validCount++;
             }
             
             parsedRows.push(rowData);
          }
          
          // Check for internal duplicates
          const skuCounts = {};
          generatedSKUs.forEach(sku => { skuCounts[sku] = (skuCounts[sku] || 0) + 1; });
          
          parsedRows.forEach(row => {
              if (row.sku && skuCounts[row.sku] > 1) {
                  row._status = 'error';
                  row._errors.push(`Duplicate SKU in file: ${row.sku}`);
                  // Adjust counts if it was valid before
                  if (row._errors.length === 1) { // Only count transition from valid to invalid once
                      validCount--;
                      invalidCount++;
                  }
              }
          });
          
          // Check DB duplicates (Batch)
          const uniqueSKUs = [...new Set(generatedSKUs)];
          const dbDuplicates = await SKUGenerator.checkBulkDuplicates(uniqueSKUs);
          
          parsedRows.forEach(row => {
              if (row.sku && dbDuplicates.includes(row.sku)) {
                  row._status = 'error';
                  row._errors.push(`SKU already exists in database: ${row.sku}`);
                   if (row._errors.length === 1 && !skuCounts[row.sku] > 1) { // Avoid double counting if already marked invalid
                      validCount--;
                      invalidCount++;
                  }
              }
          });

          resolve({
              data: parsedRows,
              errors: parsedRows.filter(r => r._status === 'error').map(r => ({ row: r._rowId, errors: r._errors })),
              summary: {
                  total: parsedRows.length,
                  valid: validCount,
                  invalid: invalidCount,
                  autoGenerated: parsedRows.filter(r => r._auto_sku || r._auto_short_code).length
              }
          });

        } catch (error) {
          reject(error);
        }
      };
      
      reader.onerror = (error) => reject(error);
      reader.readAsArrayBuffer(file);
    });
  },

  mapHeaders(headers) {
      const map = {
          fabric_name: -1,
          width: -1,
          base: -1,
          finish: -1,
          weight: -1,
          gsm: -1,
          construction: -1,
          sku: -1,
          short_code: -1,
          hsn_code: -1
      };
      
      headers.forEach((h, i) => {
          if (h.includes('fabric name') || h === 'name') map.fabric_name = i;
          else if (h === 'width') map.width = i;
          else if (h === 'base' || h.includes('base fabric')) map.base = i;
          else if (h === 'finish') map.finish = i;
          else if (h.includes('weight')) map.weight = i;
          else if (h === 'gsm') map.gsm = i;
          else if (h.includes('construction')) map.construction = i;
          else if (h === 'sku') map.sku = i;
          else if (h.includes('short code') || h === 'code') map.short_code = i;
          else if (h.includes('hsn')) map.hsn_code = i;
      });
      
      return map;
  },

  validateRow(row) {
      const errors = [];
      if (!row.fabric_name) errors.push('Fabric Name is required');
      if (!row.width) errors.push('Width is required');
      if (!row.base) errors.push('Base is required');
      
      // Clean width string to check against allowed
      const wClean = row.width.replace(/"/g, '').trim();
      if (!this.ALLOWED_WIDTHS.includes(wClean)) {
          errors.push(`Invalid Width: ${row.width}. Allowed: ${this.ALLOWED_WIDTHS.join(', ')}`);
      }
      
      return errors;
  },

  generateTemplate() {
      const headers = [
          'Fabric Name', 'Width', 'Base', 'Finish', 'Weight (kg)', 'GSM', 
          'GSM Tolerance', 'Construction', 'Yarn Type', 'Yarn Count', 
          'Handfeel', 'Stretch', 'Transparency', 'HSN Code', 'Short Code'
      ];
      
      const data = [
          ['60 x 60 Cotton', '58"', 'Cotton', 'Greige', '0.12', '110', '+/- 5%', 'Plain Weave', 'Spun', '60s', 'Soft', 'None', 'Opaque', '5208', ''],
          ['Poly Crepe', '44"', 'Polyester', 'RFD', '0.08', '80', '+/- 5%', 'Crepe', 'Filament', '80D', 'Rough', 'Mechanical', 'Semi-Sheer', '5407', '']
      ];
      
      const ws = XLSX.utils.aoa_to_sheet([headers, ...data]);
      const wb = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(wb, ws, "Template");
      XLSX.writeFile(wb, "Fabric_Import_Template.xlsx");
  }
};