import React from 'react';
import { format } from 'date-fns';

const CostSheetPrintable = ({ costSheet }) => {
  if (!costSheet) return null;

  return (
    <div id="cost-sheet-print" className="bg-white p-8 max-w-[210mm] mx-auto text-black hidden print:block">
      {/* Header */}
      <div className="border-b-2 border-black pb-4 mb-6">
        <div className="flex justify-between items-start">
          <div>
            <h1 className="text-2xl font-bold uppercase tracking-wide">Shreerang Trendz Pvt Ltd</h1>
            <p className="text-sm text-gray-600">Costing Department</p>
          </div>
          <div className="text-right">
            <h2 className="text-xl font-bold text-gray-800">COST SHEET</h2>
            <p className="text-sm mt-1">Ref: {costSheet.id.slice(0, 8).toUpperCase()}</p>
          </div>
        </div>
      </div>

      {/* Info Grid */}
      <div className="grid grid-cols-2 gap-8 mb-8">
        <div>
          <table className="w-full text-sm">
            <tbody>
              <tr>
                <td className="py-1 font-semibold w-32">Design No:</td>
                <td className="py-1">{costSheet.design_number}</td>
              </tr>
              <tr>
                <td className="py-1 font-semibold">Date:</td>
                <td className="py-1">{format(new Date(costSheet.created_at), 'dd MMM yyyy')}</td>
              </tr>
              <tr>
                <td className="py-1 font-semibold">Method:</td>
                <td className="py-1">{costSheet.costing_method || 'Standard'}</td>
              </tr>
            </tbody>
          </table>
        </div>
        <div className="flex justify-end">
           {/* Placeholder for QR Code or additional info */}
           <div className="border p-2 text-center w-32">
              <span className="text-xs text-gray-400">Yield</span>
              <div className="font-bold text-lg">{costSheet.total_saleable_mtrs} m</div>
           </div>
        </div>
      </div>

      {/* Breakdown Table */}
      <div className="mb-8">
        <h3 className="text-sm font-bold uppercase border-b border-black mb-2 pb-1">Cost Breakdown</h3>
        <table className="w-full text-sm border-collapse">
          <thead>
            <tr className="bg-gray-100">
              <th className="border p-2 text-left">Stage / Process</th>
              <th className="border p-2 text-right">Input Qty</th>
              <th className="border p-2 text-right">Shrink %</th>
              <th className="border p-2 text-right">Output Qty</th>
              <th className="border p-2 text-right">Rate (₹)</th>
              <th className="border p-2 text-right">Cost (₹)</th>
            </tr>
          </thead>
          <tbody>
            {(costSheet.cost_breakdown_by_stage || []).map((stage, idx) => (
              <tr key={idx}>
                <td className="border p-2">{stage.name}</td>
                <td className="border p-2 text-right">{stage.inputQty}</td>
                <td className="border p-2 text-right">{stage.shrink || 0}%</td>
                <td className="border p-2 text-right">{stage.outputQty}</td>
                <td className="border p-2 text-right">{stage.rate?.toFixed(2)}</td>
                <td className="border p-2 text-right font-medium">{stage.cost?.toFixed(2)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Summary Footer */}
      <div className="flex justify-end">
        <div className="w-64">
           <div className="flex justify-between py-2 border-b">
              <span className="font-semibold">Total Batch Cost:</span>
              <span>₹{costSheet.total_batch_cost?.toFixed(2)}</span>
           </div>
           <div className="flex justify-between py-2 border-b">
              <span className="font-semibold">Final Yield:</span>
              <span>{costSheet.total_saleable_mtrs} m</span>
           </div>
           <div className="flex justify-between py-3 bg-gray-100 px-2 mt-2">
              <span className="font-bold text-lg">Cost Per Meter:</span>
              <span className="font-bold text-lg">₹{costSheet.final_cost_per_mtr?.toFixed(2)}</span>
           </div>
        </div>
      </div>

      <div className="mt-12 pt-4 border-t text-xs text-center text-gray-500">
         Generated by Shreerang Costing System on {format(new Date(), 'PPpp')}
      </div>
    </div>
  );
};

export default CostSheetPrintable;